import os
import json
from tqdm import tqdm

# --- Configuration ---
# You NEED to update these variables before running the script.
#
# 1. LABELME_DIR: Folder containing all your individual LabelMe JSON files.
#    These JSON files should typically be alongside their corresponding images,
#    or at least have their 'imagePath' field correctly pointing to the image.
#    Example: LABELME_DIR = "/Users/henryli/PycharmProjects/Project-Portfolio/Automatic Protein Crystal Counter/crystal_images"
LABELME_DIR = "/some/path/to/your/labelme/annotations/"

# 2. OUT_JSON: The full path where the final COCO-like JSON file will be saved.
#    Example: OUT_JSON = "/Users/henryli/PycharmProjects/Project-Portfolio/Automatic Protein Crystal Counter/coco_annotations.json"
OUT_JSON = "/some/path/to/your/output_coco_annotations.json"

# 3. ROOT_PREFIX: The absolute path to the directory containing your images
#    *on the machine where you will run your training*. This is crucial
#    for the training framework to locate the image files.
#    If your images are going to be in '/data/my_project/images/' on the training server,
#    then ROOT_PREFIX should be '/data/my_project/images/'.
#    Ensure it ends with a trailing slash if you expect it to.
#    Example: ROOT_PREFIX = "/data/my_project/images/"
#    In the pseudo-labeling workflow, this will be dynamically set to the current
#    processed image directory.
ROOT_PREFIX = "/some/path/to/your/image/folder/on/training/machine/"


# --- Main Conversion Logic ---
def convert_labelme_to_coco():
    coco_output = {
        "info": {
            "description": "COCO-like dataset converted from LabelMe JSONs",
            "version": "1.0",
            "year": 2023,
            "contributor": "Generated by converter.py",
            "date_created": ""  # Will be filled automatically
        },
        "licenses": [],  # You can add license info if needed
        "categories": [],
        "images": [],
        "annotations": []
    }

    # Initialize counters for IDs
    image_id_counter = 0
    annotation_id_counter = 0
    category_id_counter = 0

    # Mappings for categories
    label_to_category_id = {}

    print(f"Starting conversion from '{LABELME_DIR}' to '{OUT_JSON}'...")

    # Get all LabelMe JSON files
    json_files = [f for f in os.listdir(LABELME_DIR) if f.endswith('.json')]
    if not json_files:
        print(f"No .json files found in '{LABELME_DIR}'. Please check the directory.")
        return

    for json_file_name in tqdm(json_files, desc="Processing LabelMe JSONs"):
        json_path = os.path.join(LABELME_DIR, json_file_name)

        with open(json_path, 'r', encoding='utf-8') as f:
            labelme_data = json.load(f)

        # --- Process Image Data ---
        image_id_counter += 1
        image_filename = labelme_data.get("imagePath")
        if not image_filename:
            print(f"Warning: 'imagePath' missing in {json_file_name}, skipping image.")
            continue

        # Ensure image_filename is just the basename
        image_basename = os.path.basename(image_filename)

        # Construct the full path for the COCO 'file_name' field
        # This is where ROOT_PREFIX is used
        coco_file_name = os.path.join(ROOT_PREFIX, image_basename)

        image_entry = {
            "id": image_id_counter,
            "width": labelme_data.get("imageWidth"),
            "height": labelme_data.get("imageHeight"),
            "file_name": coco_file_name,
            "license": 0,  # Placeholder
            "flickr_url": "",
            "coco_url": "",
            "date_captured": ""
        }
        coco_output["images"].append(image_entry)

        # --- Process Annotations (Shapes) ---
        for shape in labelme_data.get("shapes", []):
            if shape["shape_type"] == "rectangle":
                label = shape["label"]

                # Add category if new
                if label not in label_to_category_id:
                    category_id_counter += 1
                    label_to_category_id[label] = category_id_counter
                    coco_output["categories"].append({
                        "id": category_id_counter,
                        "name": label,
                        "supercategory": "object"  # Generic supercategory
                    })
                category_id = label_to_category_id[label]

                # LabelMe rectangles give two points (x1,y1) and (x2,y2)
                # COCO bbox is [x_min, y_min, width, height]
                points = shape["points"]
                x_coords = sorted([p[0] for p in points])
                y_coords = sorted([p[1] for p in points])

                x_min = x_coords[0]
                y_min = y_coords[0]
                width = x_coords[1] - x_coords[0]
                height = y_coords[1] - y_coords[0]

                # Calculate area
                area = width * height

                annotation_id_counter += 1
                annotation_entry = {
                    "id": annotation_id_counter,
                    "image_id": image_id_counter,
                    "category_id": category_id,
                    "bbox": [x_min, y_min, width, height],
                    "area": area,
                    "segmentation": [],  # For detection, segmentation can be an empty list
                    "iscrowd": 0  # Not crowd (individual objects)
                }
                coco_output["annotations"].append(annotation_entry)
            else:
                # You might want to handle other shape types (polygon, circle) if needed
                print(f"Warning: Skipping unsupported shape type '{shape['shape_type']}' in {json_file_name}")

    # Set date created
    coco_output["info"]["date_created"] = json.encoder.datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Save the COCO-like JSON
    with open(OUT_JSON, 'w', encoding='utf-8') as f:
        json.dump(coco_output, f, indent=4)

    print(f"\nConversion complete! COCO-like JSON saved to: {OUT_JSON}")
    print(f"Total images: {len(coco_output['images'])}")
    print(f"Total annotations: {len(coco_output['annotations'])}")
    print(f"Total categories: {len(coco_output['categories'])}")


if __name__ == "__main__":
    import datetime

    # This will be replaced by the data_split_and_convert.py script if you're using it.
    # Otherwise, manually set the configuration variables above and run this script directly.
    convert_labelme_to_coco()